name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 6 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Most used languages
        uses: lowlighter/metrics@latest
        with:
          filename: languages.svg
          token: ${{ secrets.metrics_token }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, makefile, Shell
                                     
      - name: Lastfm
        uses: lowlighter/metrics@latest
        with:
          filename: music.svg
          token: NOT_NEEDED
          plugin_music: yes
          plugin_music_provider: lastfm
          plugin_music_token: ${{ secrets.lastfm_api }}
          plugin_music_user: Coopyland
          plugin_music_mode: recent
          plugin_music_limit: 2
